### ISSUE TITLE
Database Versions

### ISSUE THREAD

**Issue by Commifreak** [leejoneshane/docker-youphptube#5]
Hi,

you need to automatically read the dbVersion-String from checkConfiguration.php and add this value as first configuration to the db. Today it inserted ver 4.0, but the source code is 5.6 and initial database as well.

=> https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/install/checkConfiguration.php#L3
=> https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/master/install/checkConfiguration.php#L3

Second problem: Every visit to a page opens a hint: You need to update the system, but the System is up-to-date?

**Comment by leejoneshane** [comment]
The version will update automatic when you complete install process.
