### ISSUE TITLE
First run experience for docker-compose

### ISSUE THREAD

**Issue by sorvis** [leejoneshane/docker-youphptube#6]
Hello,

I was testing out the docker-compose and saw a few issues:

1. The encoder and youphptube both appear to be bound to port 80 and 443 which seems to cause port conflicts?

`ERROR: for youphptube  Cannot start service youphptube: b'driver failed programming external connectivity on endpoint utube (ba7ff6755385fe32834a798569001fb49587cac780f1c07897847f4ca2457e81): Bind for 0.0.0.0:443 failed: port is already allocated'`

2.  MySql host name seems to be set wrong in the compose file
![image](https://user-images.githubusercontent.com/1037467/58098612-f0ba3200-7ba7-11e9-88af-f9656acf8df0.png)

3. Sql Database user does not have access maybe we could do something [like this](https://stackoverflow.com/a/22605418/870152) in a startup script for the MySql database?

Thank you for the help, let me know if I should try and make up a pull request with my best guess for you to review.

**Comment by leejoneshane** [comment]
You must edit the docker-compose.yml before run it. Change the environment variables to match your need, like password, connection ports, db_host name or ip etc.

**Comment by leejoneshane** [comment]
You can use official mysql:5 docker image to avoid the cache_sha2_password problem. And when you use —link mysql:db, the container named “mysql” will link to hostname “db”, so you don’t need to know the mysql container’s ip. You don’t need the depend_on things in your docker-compose.yml, because that will automatically happen when using —link.

**Comment by sorvis** [comment]
Thank you for the update to use the mysql:5 docker image. When I run it still seems to have issues with the MySql database isn't up when the application searches so it crashes. Maybe it needs a way to keep trying until it finds the database? It seems like "restart: always" added to the encoder and youphptube service may solve the problem what do you think?

Below is an example of my run showing how they crash:

> $ docker-compose up
> Creating network "original-docker-youphptube_default" with the default driver
> Creating mysql ... done
> Creating utube    ... done
> Creating encoder  ... done
> Creating sqladmin ... done
> Attaching to mysql, sqladmin, encoder, utube
> mysql         | Initializing database
> mysql         | 2019-06-04T12:27:48.763638Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> mysql         | 2019-06-04T12:27:50.077693Z 0 [Warning] InnoDB: New log files created, LSN=45790
> mysql         | 2019-06-04T12:27:50.699932Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
> mysql         | 2019-06-04T12:27:51.907257Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 2bdc27e4-86c4-11e9-b5f5-0242ac1e0002.
> mysql         | 2019-06-04T12:27:52.119157Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
> sqladmin      | phpMyAdmin not found in /var/www/html - copying now...
> sqladmin      | Complete! phpMyAdmin has been successfully copied to /var/www/html
> sqladmin      | 2019-06-04 12:27:56,816 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> sqladmin      | 2019-06-04 12:27:56,817 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
> sqladmin      | 2019-06-04 12:27:56,817 INFO Included extra file "/etc/supervisor.d/php.ini" during parsing
> sqladmin      | 2019-06-04 12:27:56,848 INFO RPC interface 'supervisor' initialized
> sqladmin      | 2019-06-04 12:27:56,848 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> sqladmin      | 2019-06-04 12:27:56,848 INFO supervisord started with pid 1
> sqladmin      | /usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
> sqladmin      |   'Supervisord is running as root and it is searching '
> mysql         | 2019-06-04T12:27:52.119892Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
> encoder       | mysqlshow: Can't connect to MySQL server on 'db' (115)
> encoder       | ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
> utube         | mysqlshow: Can't connect to MySQL server on 'db' (111 "Connection refused")
> utube         | ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111 "Connection refused")
> sqladmin      | 2019-06-04 12:27:57,874 INFO spawned: 'php-fpm' with pid 21
> sqladmin      | 2019-06-04 12:27:57,880 INFO spawned: 'nginx' with pid 22
> sqladmin      | [04-Jun-2019 12:27:58] NOTICE: fpm is running, pid 21
> sqladmin      | [04-Jun-2019 12:27:58] NOTICE: ready to handle connections
> sqladmin      | 2019-06-04 12:27:59,113 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> sqladmin      | 2019-06-04 12:27:59,113 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> encoder exited with code 1
> utube exited with code 1
> mysql         | 2019-06-04T12:28:12.178351Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178407Z 1 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178415Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178429Z 1 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178433Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178441Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178469Z 1 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
> mysql         | 2019-06-04T12:28:12.178488Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql         | Database initialized

**Comment by leejoneshane** [comment]
yes, sure.
